.travis.yml
aeron/clientconductor.go
aeron/logbuffer/FrameDescriptor.go
aeron/logbuffer/header.go
aeron/logbuffer/term/appender.go
aeron/stat/aeron_stat.go
aeron/util/memmap/memmap.go
systests/systest.go

There were a few small build breaks for go-1.11. I added a few missing Header accessors that I needed. The last commit changes the library to warn when it detects unsupported features being used instead of panicing. I found that consuming exclusive publications work OK for my use case using the regular publication code.

Build with go-1.11 and miscellaneous fixes.

---

aeron/publication.go

Fixes bug in `Offer()` whereby calling the procedure with a nil value for `reservedValueSupplier` and a length exceeding the MTU causes the program to crash.

Fix reservedValueSupplier nil bug

---

.travis.yml
aeron/atomic/buffer.go
aeron/channeluri.go
aeron/channeluri_test.go
aeron/context.go
aeron/driver/proxy.go
aeron/fragmentassembler.go
aeron/idlestrategy/backoffidlestrategy.go
aeron/image.go
aeron/logbuffer/FrameDescriptor.go
aeron/logbuffer/header.go
aeron/logbuffer/logbuffers_test.go
aeron/publication.go
aeron/publication_test.go
aeron/subscription.go
aeron/util/bits.go
go.mod
go.sum

This adds Go 1.12 modules support, bug fixes, and extra idle strategies and a ChannelUri parser.
The biggest fix here is to fix number of trailing zeros to take unsigned ints. Without this fix, some term buffer lengths would lead to crashes.

Go 1.12 modules support + fixes + extra functionality

---

aeron/clientconductor.go
aeron/logbuffer/header.go
aeron/logbuffer/logbuffers.go

Fix a leak when closing publications. 
There was also an issue here where cached publications were being returned when adding a new exclusive publication that was inconsistent with the other implementations: two exclusive publications, even on the same Aeron client, channel, stream ID, should give back two different registration IDs and will have two different session IDs. More about that here: https://aeroncookbook.com/aeron/aeron-channel-stream-session/
Also add Header.SetSessionId.

Fix publication close leak

---

aeron/clientconductor.go

Related to https://github.com/lirm/aeron-go/commit/03da701f5a2e771f90723fca8a35ad2e63c4e880.
Since the underlying slice changes during iteration (through calls to releasePublication/releaseSubscription), the iteration could run into a nil value set by https://github.com/lirm/aeron-go/blob/083126fdd27fc47191e3d5cd9bc8f0e0932e980b/aeron/clientconductor.go#L437.

Add additional nil checks to ClientConductor.Close.

---

aeron/counters/reader.go

Scan would skip counter entries with RECLAIMED (-1) recordStatus, but not increment id.
Thus, any subsequent counters would be reported with incorrect Id values.

counter reader Scan - counterId bug fix

---

aeron/clientconductor.go
aeron/counters/reader.go
aeron/subscription.go
archive/recording_pos_counter.go

subscription.go - added channelStatusID to avoid having to search for it.

counters/reader.go - removed counter-type-specific functions.

---

aeron/aeron.go

Client conductor panics when hitting an undefined error handler. There is no way to set `ClientConductor.errorHandler` from what I can tell. One way to hit this is to force an InterServiceTimeout by sleeping the running computer.
I just forwarded the context error callback similar to the other callbacks. Another approach is to if guard every errorHandler invocation.
```
2022-08-04T21:44:00.756Z	error	aeron	aeron/clientconductor.go:596	OnClientTimeout for ClientID:3
github.com/lirm/aeron-go/aeron.(*ClientConductor).OnClientTimeout
external/com_github_lirm_aeron_go/aeron/clientconductor.go:596
github.com/lirm/aeron-go/aeron/driver.(*ListenerAdapter).ReceiveMessages.func1
external/com_github_lirm_aeron_go/aeron/driver/listeneradapter.go:217 …
```

forward error handler to client conductor

---

aeron/atomic/buffer.go
aeron/clientconductor.go
aeron/command/control.go
aeron/driver/listeneradapter.go
aeron/image.go
aeron/logbuffer/header.go
aeron/position.go
aeron/subscription.go
aeron/util/bits.go
archive/archive.go
archive/control.go
archive/examples/basic_recording_publisher/basic_recording_publisher.go
archive/examples/basic_replay_merge/basic_replay_merge.go
archive/examples/examplesconfig.go
archive/options.go
archive/replaymerge/replaymerge.go

* Fix archive to use wildcard port responses and bug in replay merge
* In PollForDescriptors, don't return as soon as no fragments were read in the current poll. There could still be responses incoming.

Fix replay merge, use wildcard ports for archive responses, and fix PollForDescriptors

---

archive/replaymerge/replaymerge.go

Using the [C++ source](https://github.com/real-logic/aeron/blob/master/aeron-archive/src/main/cpp/client/ReplayMerge.h) as a model, `checkProgress` throws, and any throwable in `doWork` is caught, state set to fail, and re thrown.
This appears to also be the behavior of the Java client.
Currently, if the state machine falls into a timeout scenario and the image continues to make no progress (due to an aws ingress issue for example), then the state machine will spin in the last state it was in. This makes it difficult for the caller to "give up" and move on to reading a live subscription because ReplayMerge will not fall into a failure state.

Closer parity to C++ and Java implementation

---

aeron/subscription.go

A channel status counter is not allocated for IPC channels.
This fix is more in-line with what the Java implementation does.

subscription.ChannelStatus - return Active for IPC channels

---

archive/archive.go

refactor `NewArchive` such that any failures to build an `Archiver` cleanup any lingering resources (aeron, publication, subscription) and return a nil archiver in all error cases.

Cleanup resources on NewArchive failure

---

archive/archive.go

Otherwise, there is no way to override the error handler in Aeron, since it is copied on Connect.

In NewArchive, don't override the error listener of the Aeron context passed in.

---

aeron/clientconductor.go

Currently when the client conductor is done, we did not go through the lingering resources and close them. In the [Java](https://github.com/real-logic/aeron/blob/master/aeron-client/src/main/java/io/aeron/ClientConductor.java#L166) version, there is the CloseHelper that is doing that. This PR is to address that issue. The problem was exposed as we create a new client conductor every time we take a snapshot. Then the file descriptor of the logbuffers linger forever for every snapshot as they were not properly closed.

force closing resources at conductor close

---

aeron/logbuffer/term/appender.go
aeron/publication.go
systests/buffer_claim_message_test.go
systests/sys_test.go

When calling headerWriter.write() we need to use the beginning offset, not the resulting offset.  I also reordered/renamed a few related lines of code to unify things and help track this down.
examples/basic_publisher_claim now works.
Also add a buffer_claim_message_test, modeled after the Java test.

Fix bug in Publication.TryClaim()

---

aeron/clientconductor.go
examples/cluster/echo_service.go

Previously, the code will only break out from the switch but does not break out for the infinite for loop. 
We need to return instead so the go routine can exit, otherwise it loops forever.

fix infinite loop

---

aeron/logging/logging.go

I found this bug which is causing a lot of extra memory allocation in my critical path. I can provide pprof profiles if needed, but regardless, this is still a fix to a small bug.

log level enabled if greater than or equal to

---

cluster/cluster.go
cluster/clustered_service.go
cluster/clustered_service_agent.go
cluster/consensus_module_proxy.go

Improve documentation of cluster interfaces, and allow `ClusteredServiceAgent` to offer messages to the cluster itself. 
Comments are copied from Java implementation.
Offer capability modeled after Java Implementation:
- https://github.com/real-logic/aeron/blob/master/aeron-cluster/src/main/java/io/aeron/cluster/service/Cluster.java#L304
- https://github.com/real-logic/aeron/blob/master/aeron-cluster/src/main/java/io/aeron/cluster/service/ClusteredServiceAgent.java#L329
- https://github.com/real-logic/aeron/blob/master/aeron-cluster/src/main/java/io/aeron/cluster/service/ConsensusModuleProxy.java#L117

Enable Offer To Cluster

---

cluster/clustered_service_agent.go

Looking to make launching multiple service containers within the same cluster possible. 
While the current golang codebase has many references to multi-service support, it does not seem to support multiple services. 
The way that service mark files are created seems to be incorrect. I dug into the Java code and found that the mark file naming deviated from the Java implementation. 
https://github.com/real-logic/aeron/blob/fb8eae58b79cb5922b3522085a6a60dea50ece92/aeron-cluster/src/main/java/io/aeron/cluster/service/ClusterMarkFile.java#L414
However, even after applying the change, I was still unable to get multiple service containers to work. 
Wondering if anyone in the community knows how to make multiple service containers work.
My current debugging set-up simply spins up 2 echo …

[RFC] Multi Service Cluster

---

archive/archive.go
archive/control.go
archive/control_test.go

PollForResponse consumed responses after the response it was looking for in the incoming response stream, which specifically made it impossible to poll for replication initialization errors when setting up a replication, as they were consumed by the PollForResponse inside the Replicate operation.
This also updated PollForErrorResponse to reset the error between polls, or else it would just immediately return the previous error.
This also adds some tests for the two methods. The tests are nowhere near complete, but should give some coverage for the changes implemented here.

Use ControlledPoll for PollForResponse and PollForErrorResponse

---

archive/archive.go
archive/control.go

Check if control response connection is alive when polling for error from archive.
Changing the aeron-go `PollForErrorResponse` to check if the Control Subscription is connected to match the [C++](https://github.com/real-logic/aeron/blob/4cb1c900baaa6078b12ada7fec312ab51a49770d/aeron-archive/src/main/cpp/client/AeronArchive.h#L275-L278)/[Java](https://github.com/real-logic/aeron/blob/4cb1c900baaa6078b12ada7fec312ab51a49770d/aeron-archive/src/main/java/io/aeron/archive/client/AeronArchive.java#L435-L438) versions.
Fragment handler in PollForErrorResponse was escaping to heap due to poll argument being an interface, worked around this by making the error handler member variable casted to ControlledFragmentHandler during Archive initialization.

Fire an error in archive client when the archive disconnects

---

aeron/util/memmap/memmap.go

This happens somewhat frequently testing locally, as we try to connect to aeronmd/archive right after starting it up, when the buffers might not have been fully setup yet.

Prevent debug logging panic when mapping fails
